repos:
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        name: Run black
        args:
        - --exclude='(examples|venv|pvenv|wrapper)'

-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        name: Run PEP8
        args:
        - --in-place
        - --max-line-length=120
        - --exclude='(examples|venv|pvenv|wrapper)'
        - --ignore=E203,W503

-   repo: local
    hooks:
    -   id: pylint
        name: Run pylint
        entry: pylint
        language: python
        types:
        - python
        args:
        - --rcfile=.pylintrc
        exclude: ^(examples|wrapper|venv|pvenv|cogflow)/

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.11.2
#    hooks:
#    -   id: mypy
#        name: Run mypy
#        args:
#        - --config-file=mypy.ini

#-   repo: local
#    hooks:
#    -   id: pytest
#        name: Run Pytest
#        entry: pytest -s
#        language: system
#        pass_filenames: false
#        always_run: true
#        args:
#        - tests
#        files: \.py$
#c        exclude: ^(venv|pvenv|build|dist|examples|wrapper)/
