exclude: ^(\.venv311|\.venv|venv|pvenv|wrapper|examples)/

repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        name: Run black
        args:
          - --exclude='(\.venv311|\.venv|venv|pvenv|wrapper|examples)'

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        name: Run PEP8
        args:
          - --in-place
          - --max-line-length=120
          - --exclude='(\.venv311|\.venv|venv|pvenv|wrapper|examples)'
          - --ignore=E203,W503

  - repo: local
    hooks:
      - id: pylint
        name: Run pylint
        entry: pylint
        language: python
        types: [python]
        args:
          - --rcfile=.pylintrc
        exclude: ^(\.venv311|\.venv|venv|pvenv|wrapper|examples)/
